from tracemalloc import start
import cv2
import matplotlib.pyplot as plt
import cvlib as cv
import urllib.request
import numpy as np
import sys
from cvlib.object_detection import draw_bbox
import concurrent.futures
import math
import asyncio


 
#url='http://10.0.0.104/capture?_cb=1646718454115' Change the URL below to the URL generated by 
#the arduino software.
#rightclick the image and open in a new tab for a still image. Doesn't work with just the IP address
#Let me know (Angus) if you have any issues
url='http://192.168.1.82/capture?_cb=1649748796132'
im=None
 


    

async def run1():
    cv2.namedWindow("detection", cv2.WINDOW_AUTOSIZE)
    while True:
        img_resp=urllib.request.urlopen(url)
        imgnp=np.array(bytearray(img_resp.read()),dtype=np.uint8)
        img = cv2.imdecode(imgnp,-1)
        imgcopy = img.copy()
        bbox, label, conf = cv.detect_common_objects(img)
        img = draw_bbox(img, bbox, label, conf)
        result = imgcopy.copy()



        

        
        cv2.imshow('detection',img)
        cv2.imshow('result',result)
        key=cv2.waitKey(5)
        if key==ord('q'):
            break
            
    cv2.destroyAllWindows()
 
if __name__ == '__main__':
    print("started")

    loop = asyncio.get_event_loop()
    loop.run_until_complete(run1())

    """
    with concurrent.futures.ProcessPoolExecutor() as executer:
            f1= executer.submit(run1)
            #f2= executer.submit(run2)
    """